# Generated by Django 5.2.5 on 2025-08-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
